/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InquiriesIndexRouteImport } from './routes/inquiries.index'
import { Route as InquiriesIdRouteImport } from './routes/inquiries.$id'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesIndexRoute = InquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesIdRoute = InquiriesIdRouteImport.update({
  id: '/inquiries/$id',
  path: '/inquiries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inquiries/$id': typeof InquiriesIdRoute
  '/patients/$id': typeof PatientsIdRoute
  '/inquiries/': typeof InquiriesIndexRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inquiries/$id': typeof InquiriesIdRoute
  '/patients/$id': typeof PatientsIdRoute
  '/inquiries': typeof InquiriesIndexRoute
  '/patients': typeof PatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inquiries/$id': typeof InquiriesIdRoute
  '/patients/$id': typeof PatientsIdRoute
  '/inquiries/': typeof InquiriesIndexRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/inquiries/$id'
    | '/patients/$id'
    | '/inquiries/'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/inquiries/$id'
    | '/patients/$id'
    | '/inquiries'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/inquiries/$id'
    | '/patients/$id'
    | '/inquiries/'
    | '/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InquiriesIdRoute: typeof InquiriesIdRoute
  PatientsIdRoute: typeof PatientsIdRoute
  InquiriesIndexRoute: typeof InquiriesIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries/': {
      id: '/inquiries/'
      path: '/inquiries'
      fullPath: '/inquiries/'
      preLoaderRoute: typeof InquiriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries/$id': {
      id: '/inquiries/$id'
      path: '/inquiries/$id'
      fullPath: '/inquiries/$id'
      preLoaderRoute: typeof InquiriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InquiriesIdRoute: InquiriesIdRoute,
  PatientsIdRoute: PatientsIdRoute,
  InquiriesIndexRoute: InquiriesIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
